Projects page and project detail page
SELab-2/OSOC-3 pull request #274
Opened 2022-04-16 17:58 UTC by Tiebe-Vercoutter

In the projects page you can view the projects and filter on your own projects or by name.
<img width="694" alt="afbeelding" src="https://user-images.githubusercontent.com/99681826/163686272-aa0c8a27-ad3a-47ab-8aa0-70aeabcaf47f.png">
You can also delete a project.
<img width="512" alt="afbeelding" src="https://user-images.githubusercontent.com/99681826/163686291-1bcf7b4c-7bae-4474-9c7e-1590e17be742.png">
When clicking on the project name it takes you to that project's specific page where you can add students.
The adding of students is not completed yet but I made a placeholder to show the availible places.
<img width="733" alt="afbeelding" src="https://user-images.githubusercontent.com/99681826/163686329-6c9f3d17-70fe-41cc-afce-cf33b2a23dd9.png">

2022-04-27 14:12 UTC, stijndcl requested changes
You may want to rebase to develop because I've got a feeling there's gonna be a couple of issues (duplicate dependencies, etc).

2022-04-27 14:12 UTC, stijndcl commented on frontend/src/views/projectViews/ProjectsPage/ProjectsPage.tsx
> +            <LoadMoreContainer>
Wouldn't it be a good idea to hide this button if there are no more projects available? Button can't be used anyways, might as well.

https://reactjs.org/docs/conditional-rendering.html#inline-if-with-logical--operator

2022-04-28 07:55 UTC, stijndcl requested changes

2022-04-28 07:56 UTC, stijndcl approved these changes

2022-04-28 12:06 UTC, WardM99 requested changes
I have a random scrol bar on the page that do nothing.

![image](https://user-images.githubusercontent.com/48222993/165748111-0ef1e563-16a8-43ae-9c9b-d8e6e9795f23.png)
![image](https://user-images.githubusercontent.com/48222993/165748344-f7fbb4fc-f3ac-405e-b400-d667f29b83fe.png)

Also when I'm logged in as a coach I see the buttons for creating a project & deleting a project

2022-04-28 15:16 UTC, merged