Skill rewrite & cascade
SELab-2/OSOC-3 pull request #280
Opened 2022-04-20 10:51 UTC by FKD13

2022-05-07 18:43 UTC, FKD13 commented
Ready for review! Note this brach is branched from #344. To keep things tidy in that pr we might want to merge that first!

2022-05-08 22:19 UTC, stijndcl requested changes
One more note: there's a couple of fields that are now nullable (as requested by Miet), but I've noticed these aren't actually nullable in the Pydantic API schema's (eg. the coach/drafter/user in a Suggestion). That might cause a problem. Could you double-check on those?

2022-05-09 13:38 UTC, FKD13 commented on backend/src/app/routers/editions/projects/students/projects_students.py
> +    dependencies=[Depends(get_latest_edition), Depends(get_project_role)]
removed!

2022-05-09 13:42 UTC, FKD13 commented on backend/src/app/routers/editions/projects/projects.py
> +async def create_project(
We did discuss this in chat, we agreed on creating the project roles with separate requests

2022-05-09 14:02 UTC, FKD13 commented
Ready for review again!

2022-05-10 14:00 UTC, stijndcl commented
(You forgot the change in the message of my PR)

2022-05-11 10:38 UTC, stijndcl approved these changes

2022-05-11 10:42 UTC, merged