Students v2
SELab-2/OSOC-3 pull request #303
Opened 2022-04-27 11:30 UTC by ClementDeloof

2022-05-07 13:25 UTC, ClementDeloof commented
This PR is good for review.
Few little things i will still fix:
-linting

thing i will fix in other PR's:
-popups
-visuals

2022-05-10 14:18 UTC, stijndcl requested changes
- Lots of debug prints spamming my chrome console.
- The list of suggestions should also display the name of the person that made each suggestion
- The `Confirm Admin Suggestion` button doesn't do anything
- The `Confirm Admin Suggestion` button should not be visible to coaches
- There's a DOM validation error:
```
react-dom.development.js:67 Warning: validateDOMNesting(...): <p> cannot appear as a descendant of <p>.
    at p
    at O (http://localhost:3000/static/js/bundle.js:183933:6)
    at p
    at O (http://localhost:3000/static/js/bundle.js:183933:6)
    at div
    at O (http://localhost:3000/static/js/bundle.js:183933:6)
    at StudentInformation (http://localhost:3000/static/js/bundle.js:10253:88)
    at div
    at O (http://localhost:3000/static/js/bundle.js:183933:6)
    at StudentInfo (http://localhost:3000/static/js/bundle.js:10154:23)
    at div
    at StudentInfoPage (http://localhost:3000/static/js/bundle.js:20773:77)
    at Outlet (http://localhost:3000/static/js/bundle.js:169791:26)
    at Outlet (http://localhost:3000/static/js/bundle.js:169791:26)
    at PrivateRoute (http://localhost:3000/static/js/bundle.js:5896:70)
    at Outlet (http://localhost:3000/static/js/bundle.js:169791:26)
    at PrivateRoute (http://localhost:3000/static/js/bundle.js:5896:70)
    at Routes (http://localhost:3000/static/js/bundle.js:169883:5)
    at div
    at O (http://localhost:3000/static/js/bundle.js:183933:6)
    at div
    at O (http://localhost:3000/static/js/bundle.js:183933:6)
    at Router (http://localhost:3000/static/js/bundle.js:169816:15)
    at BrowserRouter (http://localhost:3000/static/js/bundle.js:169292:5)
    at Router (http://localhost:3000/static/js/bundle.js:356:57)
    at AuthProvider (http://localhost:3000/static/js/bundle.js:16408:5)
    at App
```

2022-05-10 14:35 UTC, stijndcl requested changes
Some docstring comments on components wouldn't hurt for our docs.

2022-05-14 09:09 UTC, stijndcl approved these changes

2022-05-14 09:12 UTC, merged