Create project skills
SELab-2/OSOC-3 pull request #395
Opened 2022-05-12 19:47 UTC by Tiebe-Vercoutter

You can now add skills/projectRoles to a project when creating one!
Also toasts

2022-05-20 20:30 UTC, FKD13 commented
Merge conflicts :o

2022-05-20 23:19 UTC, stijndcl submitted a review, later dismissed

2022-05-20 23:46 UTC, stijndcl requested changes

2022-05-20 23:46 UTC, stijndcl commented on frontend/src/data/interfaces/projects.ts
> +    infoUrl: string;
This is nullable in the backend
```suggestion
    infoUrl?: string | null;
```

2022-05-21 08:52 UTC, stijndcl approved these changes

2022-05-21 09:16 UTC, merged