add websocket basics
SELab-2/OSOC-3 pull request #415
Opened 2022-05-14 15:53 UTC by FKD13

2022-05-16 21:57 UTC, FKD13 commented
This PR adds websockets. All the internals are tested & work. Writing tests for the websocket endpoint itself proves hard, but worked when tested manually. I don't think its worth my time to try to fix this anyhow.

Testing manually can be done with swagger for the api requests and `python -m websockets <url>` for the websocket part.

2022-05-17 06:08 UTC, stijndcl commented
OUR COVERAAAAGE :cry: 

I understand tho, websockets are a pain to test.

2022-05-17 12:44 UTC, stijndcl requested changes

2022-05-17 12:44 UTC, stijndcl commented on backend/src/app/routers/editions/editions.py
> +        _: User = Depends(require_coach_ws)
Instead of an unused variable, wouldn't this be better off as a dependency in the decorator?

2022-05-17 12:44 UTC, stijndcl commented on backend/src/app/utils/websockets.py
> +                del path_ids['edition_name']
This has no effect because it's a copy of the original & never used afterwards

2022-05-17 12:44 UTC, stijndcl commented on backend/src/database/crud/projects.py
> +    # await db.refresh(project)
Commented code

2022-05-17 12:44 UTC, stijndcl commented on backend/src/database/crud/projects_students.py
> +    print(project_role_suggestion)
debug print

2022-05-17 12:47 UTC, FKD13 commented on backend/src/app/routers/editions/editions.py
> +        _: User = Depends(require_coach_ws)
Yes It would, but sadly not possible with the websocket decorator.

2022-05-17 12:48 UTC, stijndcl commented on backend/src/app/routers/editions/editions.py
> +        _: User = Depends(require_coach_ws)
Oh okay, didn't know. Thanks.

2022-05-17 12:56 UTC, stijndcl approved these changes

2022-05-17 12:57 UTC, merged