Students: infinte scroll + refactor
SELab-2/OSOC-3 pull request #418
Opened 2022-05-15 11:22 UTC by SeppeM8

- fixes #414 
- Refactor: Moved api calls from *StudentsPage.tsx* & *StudentsInfoPage.tsx* to *StudentListFilters.tsx* to remove duplicate code

2022-05-15 16:11 UTC, stijndcl approved these changes

2022-05-15 16:13 UTC, stijndcl requested changes
When I add roles, and no results are found, and then I reset the filters, the original list is not retrieved anymore & the dropdown keeps saying "no results found". Shouldn't it show the original (pre-filtering) list when I remove the filters?

2022-05-16 15:07 UTC, ClementDeloof approved these changes
Infinite scroll looks good!

2022-05-16 15:56 UTC, stijndcl approved these changes
Apparently the roles changes are for a future pr so should be fine

2022-05-16 16:58 UTC, merged