Toasts instead of error-texts
SELab-2/OSOC-3 pull request #444
Opened 2022-05-17 13:42 UTC by SeppeM8

fixes #416 
fixes #417 
Also changed for projectspage & state history page

2022-05-17 15:29 UTC, Tiebe-Vercoutter requested changes
Instead of using try catch blocks you can do toast.promise

2022-05-17 15:30 UTC, stijndcl commented
> Instead of using try catch blocks you can do toast.promise
> 
> https://fkhadra.github.io/react-toastify/promise

Great catch, the promise toasts are fancy as hell.

2022-05-18 08:43 UTC, stijndcl submitted a review, later dismissed
Two main things:
- Retrieve is a bit of a nicer word to use than receive, because it fails to fetch them.
- The toast.promise() should already show the `error` message if the request fails. It shouldn't be necessary to check & do this manually again afterwards.

2022-05-18 08:43 UTC, stijndcl commented on frontend/src/components/AdminsComponents/AddAdmin.tsx
> +            error: "Failed to receive users",
```suggestion
            error: "Failed to retrieve users",
```

2022-05-18 08:43 UTC, stijndcl commented on frontend/src/components/AdminsComponents/AddAdmin.tsx
>          }
I don't think this is necessary. The `error` string in `toast.promise()` should already do this automatically?

2022-05-18 08:43 UTC, stijndcl commented on frontend/src/components/AdminsComponents/AddAdmin.tsx
> +                        </Button>
Perhaps use the common button

2022-05-18 08:43 UTC, stijndcl commented on frontend/src/components/AdminsComponents/RemoveAdmin.tsx
> +            });
Same as above, toast.promise() does this automatically

2022-05-18 08:43 UTC, stijndcl commented on frontend/src/components/StudentsComponents/StudentListFilters/StudentListFilters.tsx
> +            { error: "Failed to receive students" }
```suggestion
            { error: "Failed to retrieve students" }
```

2022-05-18 08:43 UTC, stijndcl commented on frontend/src/components/UsersComponents/Coaches/CoachesComponents/AddCoach.tsx
> +            error: "Failed to receive users",
```suggestion
            error: "Failed to retrieve users",
```

2022-05-18 08:43 UTC, stijndcl commented on frontend/src/components/UsersComponents/Coaches/CoachesComponents/AddCoach.tsx
>          }
Same as above

2022-05-18 08:43 UTC, stijndcl commented on frontend/src/components/UsersComponents/Coaches/CoachesComponents/RemoveCoach.tsx
> +            });
Same as above

2022-05-18 08:43 UTC, stijndcl commented on frontend/src/components/UsersComponents/Requests/Requests.tsx
> +            error: "Failed to receive requests",
```suggestion
            error: "Failed to retrieve requests",
```

2022-05-18 08:43 UTC, stijndcl commented on frontend/src/components/UsersComponents/Requests/RequestsComponents/AcceptReject.tsx
> +            });
Same as above

2022-05-18 08:43 UTC, stijndcl commented on frontend/src/components/UsersComponents/Requests/RequestsComponents/AcceptReject.tsx
>          }
Same as above

2022-05-18 08:43 UTC, stijndcl commented on frontend/src/views/MailOverviewPage/MailOverviewPage.tsx
> +            { error: "Failed to receive states" }
```suggestion
            { error: "Failed to retrieve states" }
```

2022-05-18 08:43 UTC, stijndcl commented on frontend/src/views/UsersPage/UsersPage.tsx
> +            { error: "Failed to receive coaches" }
```suggestion
            { error: "Failed to retrieve coaches" }
```

2022-05-18 08:43 UTC, stijndcl commented on frontend/src/views/projectViews/ProjectsPage/ProjectsPage.tsx
> +            { error: "Failed to receive projects" }
```suggestion
            { error: "Failed to retrieve projects" }
```

2022-05-18 08:43 UTC, stijndcl commented on frontend/src/views/projectViews/ProjectsPage/ProjectsPage.tsx
>          }
Same as above

2022-05-20 00:04 UTC, stijndcl approved these changes

2022-05-20 05:37 UTC, merged