Copy student url
SELab-2/OSOC-3 pull request #452
Opened 2022-05-17 22:50 UTC by ClementDeloof

2022-05-18 19:59 UTC, Tiebe-Vercoutter approved these changes
Good functionality! Maybe at something visual to show to the user that the copy to clipboard has happened (a toast or change the text for a few seconds) but low priority.

2022-05-18 21:01 UTC, stijndcl requested changes

2022-05-18 21:11 UTC, stijndcl requested changes

2022-05-18 21:11 UTC, stijndcl commented on frontend/src/components/StudentInfoComponents/StudentCopyLink/StudentCopyLink.tsx
> +        navigator.clipboard.writeText(window.location.href);
Also, like Tiebe mentioned, a quick way to notify the user that it was successful doesn't hurt.

```ts
toast.info("URL copied to clipboard.")
```
I agree it isn't the highest of priorities, but it's literally one line. Might as well.

2022-05-19 08:45 UTC, stijndcl requested changes

2022-05-19 08:45 UTC, stijndcl commented on frontend/src/components/StudentInfoComponents/StudentCopyLink/StudentCopyLink.tsx
> +        toast.success("Copied student URL to clipboard!", { autoClose: 1000 });
Maybe remove the `{ autoClose: 1000 }`, I feel like 1 second is a bit fast. The default value is fine.

2022-05-19 17:39 UTC, stijndcl approved these changes

2022-05-19 17:39 UTC, merged