Project detail page (add students)
SELab-2/OSOC-3 pull request #461
Opened 2022-05-18 11:36 UTC by Tiebe-Vercoutter

Currently looks like this
<img width="1409" alt="afbeelding" src="https://user-images.githubusercontent.com/99681826/169029629-7ec45df1-f032-43e4-9965-1b853e4c6b15.png">

<img width="1409" alt="afbeelding" src="https://user-images.githubusercontent.com/99681826/169029699-0fce75fe-74a1-4665-8d9f-8c04966c7487.png">

Supports dnd: drag students to skills to add them

2022-05-20 23:42 UTC, stijndcl requested changes

2022-05-20 23:42 UTC, stijndcl commented on frontend/src/components/ProjectDetailComponents/ProjectCoaches/ProjectCoaches.tsx
> +                                console.log(_index);
Leftover debug print
```suggestion
```

2022-05-20 23:43 UTC, stijndcl commented
Doesn't this branch from #395? Might want to change the base of the PR if so.

2022-05-20 23:51 UTC, stijndcl requested changes
InfoUrl is nullable. If this is used anywhere else in the code (I don't think it is), make sure to add a null check there as well.

2022-05-20 23:51 UTC, stijndcl commented on frontend/src/views/projectViews/ProjectDetailPage/ProjectDetailPage.tsx
> +                    </MoreInfoLink>
Seeing as the infoUrl is nullable, this should only be rendered if the url is not null. (Just use a basic `{project.infoUrl !== null && <Component />}` conditional render).
```suggestion
                    <MoreInfoLink>
                        <CreateButton
                            showIcon={false}
                            label="More info about this project"
                            onClick={() => window.open(project.infoUrl)}
                        />
                    </MoreInfoLink>
```

2022-05-21 07:40 UTC, Tiebe-Vercoutter commented
> Doesn't this branch from #395? Might want to change the base of the PR if so.

I think so yes. So first merge this one into #395 ?

2022-05-21 07:44 UTC, stijndcl commented
> > Doesn't this branch from #395? Might want to change the base of the PR if so.
> 
> I think so yes. So first merge this one into #395 ?

Up to you, I just didn't want anyone accidentally merging this one first. It's your choice which one gets merged.

2022-05-21 07:54 UTC, Tiebe-Vercoutter commented
> 
> Up to you, I just didn't want anyone accidentally merging this one first. It's your choice which one gets merged.

Yes okay this one can go into #395 and that one into develop. Solved the merge conflicts

2022-05-21 07:59 UTC, merged