add info_url to projects
SELab-2/OSOC-3 pull request #515
Opened 2022-05-18 19:51 UTC by FKD13

2022-05-19 08:37 UTC, BertGuillemyn requested changes
Looks good overall, just one small remark about the validator.

2022-05-19 08:37 UTC, BertGuillemyn commented on backend/src/app/schemas/projects.py
> +
In src/app/schemas, there is a `validators.py` file where all of these validators should be placed. Could you move this there? A small test for the validator would also be nice.

2022-05-20 14:08 UTC, BertGuillemyn approved these changes

2022-05-20 14:21 UTC, stijndcl approved these changes

2022-05-20 14:46 UTC, merged