Skills from webhook
SELab-2/OSOC-3 pull request #522
Opened 2022-05-19 21:01 UTC by WardM99

close #265

2022-05-20 15:03 UTC, FKD13 requested changes
Looks good, one simplification can be made :)

2022-05-20 16:16 UTC, stijndcl requested changes
Missing comma (syntax error).

2022-05-20 16:16 UTC, stijndcl commented on backend/src/app/logic/webhooks.py
> +        'edition': edition
```suggestion
        'edition': edition,
```

2022-05-21 00:12 UTC, stijndcl approved these changes

2022-05-21 09:49 UTC, FKD13 approved these changes

2022-05-21 10:24 UTC, merged